language: python

dist: bionic

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  - pip

services:
  - docker

env:
  global:
    - CC_TEST_REPORTER_ID=a05b1f0da35f0716b773caf151b460f457b0e407e5ff164b061752e1555ef9d1

notifications:
  email:
    on_success: always
    on_failure: always

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - $HOME/.poetry/bin/poetry config virtualenvs.in-project true
  - $HOME/.poetry/bin/poetry install -v -E madx

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - $HOME/.poetry/bin/poetry run pytest --verbose -p no:sugar

after_script:
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
