name: PHD
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - appnope=0.1.0
  - astroid=2.3.3
  - attrs=19.3.0
  - babel=2.7.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cmarkgfm=0.4.2
  - coverage=5.0.3
  - cryptography=2.8
  - cycler=0.10.0
  - decorator=4.4.1
  - docutils=0.15.2
  - fastcache=1.1.0
  - freetype=2.10.0
  - future=0.18.2
  - gmp=6.1.2
  - gmpy2=2.1.0b1
  - h5py=2.10.0
  - hdf5=1.10.5
  - idna=2.8
  - imagesize=1.1.0
  - importlib_metadata=1.3.0
  - ipykernel=5.1.3
  - ipython=7.10.2
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.1
  - jpype1=0.7
  - jupyter_client=5.3.3
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - llvm-openmp=9.0.0
  - llvmlite=0.30.0
  - markupsafe=1.1.1
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mccabe=0.6.1
  - more-itertools=8.0.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - ncurses=6.1
  - numba=0.46.0
  - numpy=1.17.3
  - openssl=1.1.1d
  - packaging=19.2
  - pandas=0.25.3
  - parso=0.5.2
  - patsy=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - pkginfo=1.5.0.1
  - pluggy=0.12.0
  - prompt_toolkit=3.0.2
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycparser=2.19
  - pygments=2.5.2
  - pylint=2.4.4
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pysocks=1.7.1
  - pytest=5.3.2
  - python=3.7.3
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.1
  - readline=8.0
  - readme_renderer=24.0
  - requests=2.22.0
  - requests-toolbelt=0.9.1
  - scikit-learn=0.22
  - scipy=1.3.2
  - seaborn=0.10.0
  - setuptools=42.0.2
  - six=1.13.0
  - snowballstemmer=2.0.0
  - sphinx=2.3.0
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sqlite=3.30.1
  - statsmodels=0.9.0
  - sympy=1.5.1
  - tbb=2019.9
  - tk=8.6.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - twine=2.0.0
  - urllib3=1.25.7
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - wrapt=1.11.2
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - cmmnbuild-dep-manager==2.2.5
    - fsbox==0.2.0
    - generic-parser==1.0.6
    - pyhdtoolkit==0.3.0
    - pytimber==2.7.0
    - sdds==0.1.3
    - tfs-pandas==1.0.3
    - tqdm==4.42.0