name: PHD
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - attrs=20.1.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cffi=1.14.2
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fastparquet=0.4.1
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.6
  - icu=58.2
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.1.1
  - numpy-base=1.19.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - prompt_toolkit=3.0.7
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.6
  - qtpy=1.9.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tbb=2020.2
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - chardet==3.0.4
    - colorama==0.4.3
    - commonmark==0.9.1
    - cycler==0.10.0
    - h5py==2.10.0
    - idna==2.10
    - iniconfig==1.0.1
    - joblib==0.16.0
    - kiwisolver==1.2.0
    - llvmlite==0.33.0
    - loguru==0.5.2
    - matplotlib==3.3.1
    - more-itertools==8.5.0
    - numba==0.50.1
    - numpy==1.19.2
    - pandas==0.25.3
    - patsy==0.5.1
    - pillow==7.2.0
    - pluggy==0.13.1
    - py==1.9.0
    - pyarrow==1.0.1
    - pygments==2.7.0
    - pyhdtoolkit==0.5.0
    - pytest==6.0.2
    - requests==2.24.0
    - rich==5.2.1
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - seaborn==0.11.0
    - statsmodels==0.12.0
    - tfs-pandas==1.0.5
    - threadpoolctl==2.1.0
    - thrift==0.13.0
    - toml==0.10.1
    - typing-extensions==3.7.4.3
