name: PHD
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - arrow-cpp=0.15.1
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - boost-cpp=1.71.0
  - brotli=1.0.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - cycler=0.10.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - double-conversion=3.1.5
  - entrypoints=0.3
  - expat=2.2.9
  - fastcache=1.1.0
  - fastparquet=0.3.2
  - fontconfig=2.13.0
  - freetype=2.10.2
  - gflags=2.2.2
  - glib=2.65.0
  - glog=0.4.0
  - gmp=6.1.2
  - gmpy2=2.0.8
  - grpc-cpp=1.26.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.1
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libboost=1.71.0
  - libedit=3.1.20191231
  - libevent=2.1.8
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.33.0
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - more-itertools=8.4.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.0.3
  - numba=0.50.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=0.25.3
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pluggy=0.13.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - py=1.9.0
  - pyarrow=0.15.1
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.3
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - re2=2019.08.01
  - readline=8.0
  - requests=2.24.0
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - send2trash=1.5.0
  - setuptools=49.2.0
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.32.3
  - statsmodels=0.11.1
  - sympy=1.6.1
  - tbb=2020.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - thrift=0.13.0
  - thrift-cpp=0.11.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - uriparser=0.9.3
  - urllib3=1.25.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cmmnbuild-dep-manager==2.5.0
    - cpymad==1.4.1
    - generic-parser==1.0.6
    - importlib-resources==3.0.0
    - jpype1==1.0.1
    - loguru==0.4.1
    - minrpc==0.0.11
    - pip==20.2.1
    - pyhdtoolkit==0.4.1
    - pynaff==1.1.4
    - pytimber==3.0.0
    - sdds==0.1.3
    - tfs-pandas==1.0.5
    - typing-extensions==3.7.4.2
