name: PHD
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - alsa-lib=1.2.3
  - argon2-cffi=21.1.0
  - arrow-cpp=5.0.0
  - async_generator=1.10
  - attrs=21.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=21.11b0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - colorama=0.4.4
  - commonmark=0.9.1
  - cramjam=2.3.1
  - cryptography=35.0.0
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fastparquet=0.7.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.10.1
  - future=0.18.2
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glib=2.70.0
  - glib-tools=2.70.0
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.0b5
  - grpc-cpp=1.40.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5py=3.4.0
  - hdf5=1.12.1
  - icu=68.1
  - idna=3.1
  - importlib-metadata=4.8.2
  - importlib_resources=5.4.0
  - ipykernel=6.4.2
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=4.2.1
  - jupyter_client=7.0.6
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.79.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.18.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.3.0
  - libutf8proc=2.6.1
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvmlite=0.37.0
  - loguru=0.5.3
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - mypy_extensions=0.4.3
  - mysql-common=8.0.27
  - mysql-libs=8.0.27
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.6
  - nspr=4.30
  - nss=3.69
  - numba=0.54.1
  - numpy=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - optics_functions=0.1.1
  - orc=1.7.0
  - packaging=21.3
  - pandas=1.3.4
  - pandoc=2.16.1
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.2
  - pathspec=0.9.0
  - patsy=0.5.2
  - pcre=8.45
  - pendulum=2.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.3.1
  - platformdirs=2.3.0
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.21
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pyarrow=5.0.0
  - pycparser=2.20
  - pydantic=1.8.2
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - pytzdata=2020.1
  - pyzmq=22.3.0
  - qt=5.12.9
  - re2=2021.09.01
  - readline=8.1
  - regex=2021.11.10
  - requests=2.26.0
  - rich=10.14.0
  - s2n=1.0.10
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - sdds=0.2.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=58.2.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - statsmodels=0.13.0
  - sympy=1.9
  - terminado=0.12.1
  - testpath=0.5.0
  - tfs-pandas=3.0.2
  - threadpoolctl=3.0.0
  - thrift=0.14.0
  - tk=8.6.11
  - tomli=1.2.2
  - tornado=6.1
  - traitlets=5.1.0
  - typed-ast=1.5.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - cpymad==1.9.0
    - importlib-resources==5.3.0
    - jupyterlab-widgets==1.0.2
    - minrpc==0.1.0
    - pyhdtoolkit==0.15.1
