# Runs all tests and pushes coverage report to codeclimate
name: Coverage

defaults:
  run:
    shell: bash

on:  # Runs on all push events to master branch and any push related to a pull request
  push:
    branches:
      - master
  pull_request:  # so that codeclimate gets coverage and reports on the diff

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
        python-version: 3.12

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      - name: Set up Python ${{ env.python-version }}
        run: uv python install ${{ env.python-version }}

      - name: Install package with test dependencies
        run: uv sync --all-extras --dev

      - name: Get acc-models-lhc
        run: git clone -b 2022 https://gitlab.cern.ch/acc-models/acc-models-lhc.git --depth 1

      - name: Run all tests
        run: uv run pytest -n auto -v
        # run: make alltests

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
